# Generated by Django 3.0.8 on 2020-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answervote_questionvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
