# Generated by Django 3.0.8 on 2020-08-08 08:45

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200802_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, storage=main.models.OverwriteStorage(), upload_to=main.models.get_image_path),
        ),
    ]
